import { jsPDF } from "jspdf";
import { readFileSync } from "fs";
import { join } from "path";

export interface PdfGenerationOptions {
  templateName: string;
  templateContent: string;
  formData: Record<string, any>;
  logoPath?: string;
}

export async function generatePDF(options: PdfGenerationOptions): Promise<Buffer> {
  const { templateName, templateContent, formData } = options;

  // Create new PDF document (A4 size)
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 25;
  const contentWidth = pageWidth - 2 * margin;

  // Add watermark logo in background
  try {
    const logoPath = join(process.cwd(), "attached_assets", "logo12_1761193592383.png");
    const logoData = readFileSync(logoPath).toString("base64");
    const logoImage = `data:image/png;base64,${logoData}`;
    
    // Add centered watermark at 10% opacity
    const logoSize = 80;
    const logoX = (pageWidth - logoSize) / 2;
    const logoY = (pageHeight - logoSize) / 2;
    doc.saveGraphicsState();
    doc.setGState(new doc.GState({ opacity: 0.1 }));
    doc.addImage(logoImage, "PNG", logoX, logoY, logoSize, logoSize);
    doc.restoreGraphicsState();
  } catch (error) {
    console.error("Error adding logo watermark:", error);
  }

  // Add header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(templateName, margin, margin);

  // Add generation date
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const dateText = `Generated on: ${new Date().toLocaleDateString("en-IN", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })}`;
  doc.text(dateText, margin, margin + 10);

  // Add separator line
  doc.setLineWidth(0.5);
  doc.line(margin, margin + 15, pageWidth - margin, margin + 15);

  // Replace placeholders in template content
  let content = templateContent;
  Object.entries(formData).forEach(([key, value]) => {
    const placeholder = new RegExp(`{{${key}}}`, "g");
    content = content.replace(placeholder, value || "[Not provided]");
  });

  // Add content
  doc.setFontSize(11);
  doc.setFont("times", "normal");
  const lines = doc.splitTextToSize(content, contentWidth);
  
  let yPosition = margin + 25;
  const lineHeight = 7;
  const linesPerPage = Math.floor((pageHeight - margin * 2 - 30) / lineHeight);

  lines.forEach((line: string, index: number) => {
    if (index > 0 && index % linesPerPage === 0) {
      doc.addPage();
      yPosition = margin;
    }
    doc.text(line, margin, yPosition);
    yPosition += lineHeight;
  });

  // Add footer with page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
    
    // Add "Satyagrah.AI" branding
    doc.setFontSize(8);
    doc.text(
      "Generated by Satyagrah.AI - Legal Assistance Platform",
      margin,
      pageHeight - 10
    );
  }

  // Convert to buffer
  const pdfData = doc.output("arraybuffer");
  return Buffer.from(pdfData);
}
